import type { Metadata } from 'next'
import './globals.css'
import Header from './Components/Header'
import Aside from './Components/Aside'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Aside />
        {children}
      </body>
    </html>
  )
}
